# Generated by Django 6.0 on 2025-12-17 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadhabitacional',
            options={'ordering': ['torre', 'numero'], 'verbose_name_plural': 'Unidades Habitacionales'},
        ),
        migrations.AddField(
            model_name='residente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='residentes/fotos/'),
        ),
        migrations.AlterField(
            model_name='alertaseguridad',
            name='url_evidencia',
            field=models.URLField(blank=True, help_text='Link a la evidencia (S3/Cloudinary) generado por la IA externa', null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='mes',
            field=models.CharField(help_text='Ej: Enero 2024', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalmantenimiento',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Ej: Plomería, Electricidad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='score_morosidad_ia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje (0-100) calculado por IA externa que indica probabilidad de impago.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='seguridad',
            name='turno',
            field=models.CharField(blank=True, help_text='Ej: Mañana, Tarde, Noche', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticketmantenimiento',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Técnico encargado de la incidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='api.personalmantenimiento'),
        ),
        migrations.AlterField(
            model_name='unidadhabitacional',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la unidad está ocupable'),
        ),
        migrations.AlterField(
            model_name='unidadhabitacional',
            name='numero',
            field=models.CharField(help_text='Identificador único (ej: A-101)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculoautorizado',
            name='placa',
            field=models.CharField(help_text='Placa sin guiones ni espacios para mejor validación', max_length=20, unique=True),
        ),
    ]
